# Generated by Django 4.0.4 on 2022-04-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50, verbose_name='brand')),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('Under inspection', 'Under inspection'), ('inspected', 'inspected')], max_length=50, verbose_name='status')),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('appointmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='khodro45_app.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('bider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bider', to='User.bider')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('start_price', models.PositiveBigIntegerField()),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('bider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='khodro45_app.bid')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khodro45_app.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='khodro45_app.brand'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='User.customer'),
        ),
    ]
