# Generated by Django 4.0 on 2022-04-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khodro45_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bider',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='khodro45_app.auction'),
            preserve_default=False,
        ),
    ]
