# Generated by Django 4.0 on 2022-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khodro45_app', '0002_remove_auction_bider_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
